## 1) What is PyTorch?
PyTorch is a deep learning framework built around tensors and automatic differentiation. It provides:
- Tensors with GPU acceleration
- Autograd for automatic gradients
- Modules for building neural networks
- Optimizers and training utilities

In [1]:
import torch
print(torch.__version__)

2.10.0+cpu


## 2) Tensors and basic creation
Tensors are n-dimensional arrays. You can create them from lists, NumPy arrays, or with helpers.

In [2]:
import torch

# Scalars, vectors, matrices
scalar = torch.tensor(3.14)
vector = torch.tensor([1.0, 2.0, 3.0])
matrix = torch.tensor([[1, 2], [3, 4]])

print(scalar, scalar.shape)
print(vector, vector.shape)
print(matrix, matrix.shape)

# Common initializations
zeros = torch.zeros((2, 3))
ones = torch.ones((2, 3))
rand = torch.rand((2, 3))

print(zeros)
print(ones)
print(rand)

tensor(3.1400) torch.Size([])
tensor([1., 2., 3.]) torch.Size([3])
tensor([[1, 2],
        [3, 4]]) torch.Size([2, 2])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.3401, 0.2170, 0.1431],
        [0.0161, 0.7974, 0.4734]])


## 3) Tensor attributes and device
Tensors carry dtype and device (CPU/GPU). Use `.to(device)` to move them.

In [3]:
x = torch.randn(3, 3, dtype=torch.float32)
print(x.dtype, x.device)

# If CUDA is available, move to GPU
if torch.cuda.is_available():
    x = x.to('cuda')
    print('moved to', x.device)

torch.float32 cpu
